# Generated by Django 3.2.5 on 2021-07-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_alter_statement_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankingdata',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DONE', 'DONE'), ('ERROR', 'ERROR')], default='PENDING', max_length=30),
        ),
    ]
