version: '3.3'

services:

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=unnax
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=j9714697
    ports:
      - "4646:4646"

  web:
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/usr/src/app/
    ports:
      - 1337:8000
    network_mode: host
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://localhost:6379/0
      - CELERY_BACKEND=redis://localhost:6379/0
      - SQL_DATABASE=unnax_db
      - SQL_USER=unnax_user
      - SQL_PASSWORD=unnax_password
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - redis
      - db

  celery:
    build: ./project
    command: celery worker --app=unnax --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./project:/usr/src/app
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://localhost:6379/0
      - CELERY_BACKEND=redis://localhost:6379/0
    depends_on:
      - web
      - redis
    network_mode: host

  dashboard:
    build: ./project
    command:  flower -A unnax --port=5555 --broker=redis://localhost:6379/0
    ports:
      - 5555:5555
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://localhost:6379/0
      - CELERY_BACKEND=redis://localhost:6379/0
    depends_on:
      - web
      - redis
      - celery
    network_mode: host
    
  redis:
    image: redis:6-alpine
    network_mode: host














# version: '3.3'

# services:
#   web:
#     build: ./project
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - ./project:/usr/src/app/
#     ports:
#       - 1337:8000
#     environment:
#       - DEBUG=1
#       - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
#       - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
#       - CELERY_BROKER=redis://redis:6379/0
#       - CELERY_BACKEND=redis://redis:6379/0

    # extra_hosts:
    #   - "localhost1:10.0.75.1"
    # depends_on:
    #   - redis

#   celery:
#     build: ./project
#     command: celery worker --app=unnax --loglevel=info --logfile=logs/celery.log
#     volumes:
#       - ./project:/usr/src/app
#     environment:
#       - DEBUG=1
#       - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
#       - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
#       - CELERY_BROKER=redis://redis:6379/0
#       - CELERY_BACKEND=redis://redis:6379/0
#     depends_on:
#       - web
#       - redis

#   redis:
#     image: redis:6-alpine

#   dashboard:
#     build: ./project
#     command:  flower -A unnax --port=5555 --broker=redis://redis:6379/0
#     ports:
#       - 5555:5555
#     environment:
#       - DEBUG=1
#       - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
#       - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
#       - CELERY_BROKER=redis://redis:6379/0
#       - CELERY_BACKEND=redis://redis:6379/0
#     depends_on:
#       - web
#       - redis
#       - celery