version: '3.3'

services:

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=unnax
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=j9714697
    ports:
      - "4646:4646"

  web:
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/usr/src/app/
    ports:
      - 1337:8000
    network_mode: host
    environment:
      - DEBUG=$DEBUG
      - SECRET_KEY=$SECRET_KEY
      - DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS
      - CELERY_BROKER=$CELERY_BROKER
      - CELERY_BACKEND=$CELERY_BACKEND
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_USER=$DATABASE_USER
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_PORT=$DATABASE_PORT
    depends_on:
      - redis
      - db

  celery:
    build: ./project
    command: celery worker --app=unnax --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./project:/usr/src/app
    environment:
      - DEBUG=$DEBUG
      - SECRET_KEY=$SECRET_KEY
      - DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS
      - CELERY_BROKER=$CELERY_BROKER
      - CELERY_BACKEND=$CELERY_BACKEND
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_USER=$DATABASE_USER
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_PORT=$DATABASE_PORT
    depends_on:
      - web
      - redis
    network_mode: host

  dashboard:
    build: ./project
    command:  flower -A unnax --port=5555 --broker=redis://localhost:6379/0
    ports:
      - 5555:5555
    environment:
      - DEBUG=$DEBUG
      - SECRET_KEY=$SECRET_KEY
      - DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS
      - CELERY_BROKER=$CELERY_BROKER
      - CELERY_BACKEND=$CELERY_BACKEND
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_USER=$DATABASE_USER
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_PORT=$DATABASE_PORT
    depends_on:
      - web
      - redis
      - celery
    network_mode: host
    
  redis:
    image: redis:6-alpine
    network_mode: host